#!/usr/bin/env python
from pandocfilters import RawBlock, toJSONFilter

"""
This is a general div filter. Adds functions to
classes afterpage and center for LaTeX output.

Todo: Make it add 'afterpage' module to Header
      includes.
"""

def latexBlock(s):
    return RawBlock('latex', s)

def htmlBlock(s):
    return RawBlock('html', s)

def parse(key, val, fmt, meta):
    if key == 'Div':
        [[ident, classes, kvs], contents] = val
        if "afterpage" in classes and fmt == 'latex':
            return ([latexBlock('\\afterpage{')] +
                    contents +
                    [latexBlock('}')])
        if "center" in classes:
            if fmt == 'latex':
                return ([latexBlock('\\begin{center}')] +
                        contents +
                        [latexBlock('\\end{center}')])

if __name__ == "__main__":
  toJSONFilter(parse)
